//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    using LolProject2.ViewModels;
    public partial class Appeal : ViewModel
    {
        private string _tema;
        public string Tema 
        { 
            get { return _tema; }
            set => Set(ref _tema, value);
        }
        private string _opisanie;
        public string Opisanie 
        { 
            get { return _opisanie; } 
            set => Set(ref _opisanie, value);
        }
        private string _status;
        public string Status 
        { 
            get { return _status; }
            set => Set(ref _status, value);
        }
        private string _user_login;
        public string User_login 
        { 
            get { return _user_login; }
            set => Set(ref _user_login, value);
        }
        private string _admin_Login;
        public string Admin_Login 
        { 
            get { return _admin_Login; }
            set => Set(ref _admin_Login, value);
        }
        public int Id { get; set; }
        private string _otvet;
        public string Otvet 
        { 
            get { return _otvet; }
            set => Set(ref _otvet, value);
        }
    }
}
