//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    using LolProject2.ViewModels;
    public partial class Heroes : ViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heroes()
        {
            this.BaseScales = new HashSet<BaseScales>();
            this.Scales = new HashSet<Scales>();
            this.Skill_Hero = new HashSet<Skill_Hero>();
        }
        private string _nameHero;
        public string NameHero 
        { 
            get { return _nameHero; }
            set => Set(ref _nameHero, value);
        }
        private byte[] _imageHero;
        public byte[] ImageHero 
        { 
            get { return _imageHero; }
            set => Set(ref _imageHero, value);
        }
        private byte[] _imageHeroIcon;
        public byte[] ImageHeroIcon 
        { 
            get { return _imageHeroIcon; }
            set => Set(ref _imageHeroIcon, value);
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseScales> BaseScales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scales> Scales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill_Hero> Skill_Hero { get; set; }
    }
}
