//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    using LolProject2.ViewModels;
    public partial class Items: ViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Items_Difference = new HashSet<Items_Difference>();
        }
        private string _itemName;
        public string ItemName
        {
            get { return _itemName; }
            set => Set(ref _itemName, value);
        }
        private byte[] _imageItems;
        public byte[] ImageItem 
        { 
            get { return _imageItems; } 
            set => Set(ref _imageItems, value);
        }
        private Nullable<int> _ad;
        public Nullable<int> AD 
        { 
            get { return _ad; } 
            set => Set(ref _ad, value);
        }
        private Nullable<int> _crit;
        public Nullable<int> Crit 
        { 
            get { return _crit; } 
            set=>Set(ref _crit, value); 
        }
        private Nullable<int> _ap; 
        public Nullable<int> AP 
        { 
            get { return _ap; }
            set => Set(ref _ap, value); 
        }
        private Nullable<int> _attack_speed;
        public Nullable<int> Attack_speed 
        { 
            get { return _attack_speed; }
            set => Set(ref _attack_speed, value);
        }
        private Nullable<int> _movement;
        public Nullable<int> Movement 
        { 
            get { return _movement; } 
            set => Set(ref _movement, value); 
        }
        private Nullable<int> _armor;
        public Nullable<int> Armor 
        { 
            get { return _armor; } 
            set => Set(ref _armor, value); 
        }
        private Nullable<int> _hp;
        public Nullable<int> HP 
        { 
            get { return _hp; }
            set => Set(ref _hp,value); 
        }
        private string _modificators;
        public string Modificators 
        { 
            get { return _modificators; }
            set => Set(ref _modificators, value); 
        }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items_Difference> Items_Difference { get; set; }
    }
}
