//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key_skill
    {
        public string NameSkill { get; set; }
        public int KeySkill { get; set; }
        public int Id { get; set; }
    
        public virtual Keys Keys { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
