//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level_Skill
    {
        public string NameSkill { get; set; }
        public int LevelSkill { get; set; }
        public Nullable<int> Damageskills { get; set; }
        public Nullable<int> Modificatorsskills { get; set; }
        public int Id { get; set; }
    
        public virtual Levels Levels { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
