//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOLPROJECTEntities : DbContext
    {
        public LOLPROJECTEntities()
            : base("name=LOLPROJECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appeal> Appeal { get; set; }
        public virtual DbSet<BaseScales> BaseScales { get; set; }
        public virtual DbSet<Heroes> Heroes { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Items_Difference> Items_Difference { get; set; }
        public virtual DbSet<ItemsDifferents> ItemsDifferents { get; set; }
        public virtual DbSet<Key_skill> Key_skill { get; set; }
        public virtual DbSet<Keys> Keys { get; set; }
        public virtual DbSet<Level_Skill> Level_Skill { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<Levels_Hero> Levels_Hero { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Scales> Scales { get; set; }
        public virtual DbSet<Skill_Hero> Skill_Hero { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
