//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    using LolProject2.ViewModels;
    public partial class Skill_Hero : ViewModel
    {
        private string _nameskill;
        public string Nameskill 
        { 
            get { return _nameskill; }
            set =>  Set(ref _nameskill, value);
        }
        private string _nameHero;
        public string NameHero 
        { 
            get { return _nameHero; } 
            set => Set(ref _nameHero, value); 
        }
        public int Id { get; set; }
    
        public virtual Heroes Heroes { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
