//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolProject2
{
    using System;
    using System.Collections.Generic;
    using LolProject2.ViewModels;
    public partial class Skills : ViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skills()
        {
            this.Key_skill = new HashSet<Key_skill>();
            this.Level_Skill = new HashSet<Level_Skill>();
            this.Skill_Hero = new HashSet<Skill_Hero>();
        }
        private string _nameSkills;
        public string NameSkills
        {
            get { return _nameSkills; }
            set => Set(ref _nameSkills, value);
        }
        private string _opisanie;
        public string Opisanie 
        { 
            get { return _opisanie; }
            set => Set(ref _opisanie, value); 
        }
        private byte[] _imageSkill;
        public byte[] ImageSkill 
        { 
            get { return _imageSkill; }
            set => Set(ref _imageSkill, value); 
        }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Key_skill> Key_skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Level_Skill> Level_Skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill_Hero> Skill_Hero { get; set; }
    }
}
